<h2 style = "color : Brown"> Case Study - Cricket Tournament </h2>

A panel wants to select players for an upcoming league match based on their fitness. Players from all significant cricket clubs have participated in a practice match, and their data is collected. Let us now explore NumPy features using the player's data.</font>

<h4 style = "color : Sky blue"> Example - 1</h4>  

#### Heights of the players is stored as a regular Python list: height_in. The height is expressed in inches. Can you make a numpy array out of it ?

In [1]:
# Define list
heights = [74, 74, 72, 72, 73, 69, 69, 71, 76, 71, 73, 73, 74, 74, 69, 70, 73, 75, 78, 79, 76, 74, 76, 72, 71, 75, 77, 74, 73, 74, 78, 73, 75, 73, 75, 75, 74, 69, 71, 74, 73, 73, 76, 74, 74, 70, 72, 77, 74, 70, 73, 75, 76, 76, 78, 74, 74, 76, 77, 81, 78, 75, 77, 75, 76, 74, 72, 72, 75, 73, 73, 73, 70, 70, 70, 76, 68, 71, 72, 75, 75, 75, 75, 68, 74, 78, 71, 73, 76, 74, 74, 79, 75, 73, 76, 74, 74, 73, 72, 74, 73, 74, 72, 73, 69, 72, 73, 75, 75, 73, 72, 72, 76, 74, 72, 77, 74, 77, 75, 76, 80, 74, 74, 75, 78, 73, 73, 74, 75, 76, 71, 73, 74, 76, 76, 74, 73, 74, 70, 72, 73, 73, 73, 73, 71, 74, 74, 72, 74, 71, 74, 73, 75, 75, 79, 73, 75, 76, 74, 76, 78, 74, 76, 72, 74, 76, 74, 75, 78, 75, 72, 74, 72, 74, 70, 71, 70, 75, 71, 71, 73, 72, 71, 73, 72, 75, 74, 74, 75, 73, 77, 73, 76, 75, 74, 76, 75, 73, 71, 76, 75, 72, 71, 77, 73, 74, 71, 72, 74, 75, 73, 72, 75, 75, 74, 72, 74, 71, 70, 74, 77, 77, 75, 75, 78, 75, 76, 73, 75, 75, 79, 77, 76, 71, 75, 74, 69, 71, 76, 72, 72, 70, 72, 73, 71, 72, 71, 73, 72, 73, 74, 74, 72, 75, 74, 74, 77, 75, 73, 72, 71, 74, 77, 75, 75, 75, 78, 78, 74, 76, 78, 76, 70, 72, 80, 74, 74, 71, 70, 72, 71, 74, 71, 72, 71, 74, 69, 76, 75, 75, 76, 73, 76, 73, 77, 73, 72, 72, 77, 77, 71, 74, 74, 73, 78, 75, 73, 70, 74, 72, 73, 73, 75, 75, 74, 76, 73, 74, 75, 75, 72, 73, 73, 72, 74, 78, 76, 73, 74, 75, 70, 75, 71, 72, 78, 75, 73, 73, 71, 75, 77, 72, 69, 73, 74, 72, 70, 75, 70, 72, 72, 74, 73, 74, 76, 75, 80, 72, 75, 73, 74, 74, 73, 75, 75, 71, 73, 75, 74, 74, 72, 74, 74, 74, 73, 76, 75, 72, 73, 73, 73, 72, 72, 72, 72, 71, 75, 75, 74, 73, 75, 79, 74, 76, 73, 74, 74, 72, 74, 74, 75, 78, 74, 74, 74, 77, 70, 73, 74, 73, 71, 75, 71, 72, 77, 74, 70, 77, 73, 72, 76, 71, 76, 78, 75, 73, 78, 74, 79, 75, 76, 72, 75, 75, 70, 72, 70, 74, 71, 76, 73, 76, 71, 69, 72, 72, 69, 73, 69, 73, 74, 74, 72, 71, 72, 72, 76, 76, 76, 74, 76, 75, 71, 72, 71, 73, 75, 76, 75, 71, 75, 74, 72, 73, 73, 73, 73, 76, 72, 76, 73, 73, 73, 75, 75, 77, 73, 72, 75, 70, 74, 72, 80, 71, 71, 74, 74, 73, 75, 76, 73, 77, 72, 73, 77, 76, 71, 75, 73, 74, 77, 71, 72, 73, 69, 73, 70, 74, 76, 73, 73, 75, 73, 79, 74, 73, 74, 77, 75, 74, 73, 77, 73, 77, 74, 74, 73, 77, 74, 77, 75, 77, 75, 71, 74, 70, 79, 72, 72, 70, 74, 74, 72, 73, 72, 74, 74, 76, 82, 74, 74, 70, 73, 73, 74, 77, 72, 76, 73, 73, 72, 74, 74, 71, 72, 75, 74, 74, 77, 70, 71, 73, 76, 71, 75, 74, 72, 76, 79, 76, 73, 76, 78, 75, 76, 72, 72, 73, 73, 75, 71, 76, 70, 75, 74, 75, 73, 71, 71, 72, 73, 73, 72, 69, 73, 78, 71, 73, 75, 76, 70, 74, 77, 75, 79, 72, 77, 73, 75, 75, 75, 73, 73, 76, 77, 75, 70, 71, 71, 75, 74, 69, 70, 75, 72, 75, 73, 72, 72, 72, 76, 75, 74, 69, 73, 72, 72, 75, 77, 76, 80, 77, 76, 79, 71, 75, 73, 76, 77, 73, 76, 70, 75, 73, 75, 70, 69, 71, 72, 72, 73, 70, 70, 73, 76, 75, 72, 73, 79, 71, 72, 74, 74, 74, 72, 76, 76, 72, 72, 71, 72, 72, 70, 77, 74, 72, 76, 71, 76, 71, 73, 70, 73, 73, 72, 71, 71, 71, 72, 72, 74, 74, 74, 71, 72, 75, 72, 71, 72, 72, 72, 72, 74, 74, 77, 75, 73, 75, 73, 76, 72, 77, 75, 72, 71, 71, 75, 72, 73, 73, 71, 70, 75, 71, 76, 73, 68, 71, 72, 74, 77, 72, 76, 78, 81, 72, 73, 76, 72, 72, 74, 76, 73, 76, 75, 70, 71, 74, 72, 73, 76, 76, 73, 71, 68, 71, 71, 74, 77, 69, 72, 76, 75, 76, 75, 76, 72, 74, 76, 74, 72, 75, 78, 77, 70, 72, 79, 74, 71, 68, 77, 75, 71, 72, 70, 72, 72, 73, 72, 74, 72, 72, 75, 72, 73, 74, 72, 78, 75, 72, 74, 75, 75, 76, 74, 74, 73, 74, 71, 74, 75, 76, 74, 76, 76, 73, 75, 75, 74, 68, 72, 75, 71, 70, 72, 73, 72, 75, 74, 70, 76, 71, 82, 72, 73, 74, 71, 75, 77, 72, 74, 72, 73, 78, 77, 73, 73, 73, 73, 73, 76, 75, 70, 73, 72, 73, 75, 74, 73, 73, 76, 73, 75, 70, 77, 72, 77, 74, 75, 75, 75, 75, 72, 74, 71, 76, 71, 75, 76, 83, 75, 74, 76, 72, 72, 75, 75, 72, 77, 73, 72, 70, 74, 72, 74, 72, 71, 70, 71, 76, 74, 76, 74, 74, 74, 75, 75, 71, 71, 74, 77, 71, 74, 75, 77, 76, 74, 76, 72, 71, 72, 75, 73, 68, 72, 69, 73, 73, 75, 70, 70, 74, 75, 74, 74, 73, 74, 75, 77, 73, 74, 76, 74, 75, 73, 76, 78, 75, 73, 77, 74, 72, 74, 72, 71, 73, 75, 73, 67, 67, 76, 74, 73, 70, 75, 70, 72, 77, 79, 78, 74, 75, 75, 78, 76, 75, 69, 75, 72, 75, 73, 74, 75, 75, 73]

In [2]:
import numpy as np

heights_in = np.array(heights)

In [3]:
heights_in

array([74, 74, 72, ..., 75, 75, 73])

In [4]:
type(heights_in)

numpy.ndarray

<h4 style = "color : Sky blue"> Example - 2</h4>

#### Count the number of pariticipants

In [5]:
#way1
heights_in.size

1015

In [6]:
#way 2
len(heights_in)

1015

In [7]:
heights_in.shape

(1015,)

<h4 style = "color : Sky blue"> Example - 3</h4>

####  Convert the heights from inches to meters

In [8]:
heights_in = heights_in * 0.0254

In [9]:
heights_in

array([1.8796, 1.8796, 1.8288, ..., 1.905 , 1.905 , 1.8542])

<h4 style = "color : Sky blue"> Example - 4</h4>

#### A list of weights (in lbs) of the players is provided. Convert it to kg and calculate BMI

In [10]:
weights_lb = [180, 215, 210, 210, 188, 176, 209, 200, 231, 180, 188, 180, 185, 160, 180, 185, 189, 185, 219, 230, 205, 230, 195, 180, 192, 225, 203, 195, 182, 188, 200, 180, 200, 200, 245, 240, 215, 185, 175, 199, 200, 215, 200, 205, 206, 186, 188, 220, 210, 195, 200, 200, 212, 224, 210, 205, 220, 195, 200, 260, 228, 270, 200, 210, 190, 220, 180, 205, 210, 220, 211, 200, 180, 190, 170, 230, 155, 185, 185, 200, 225, 225, 220, 160, 205, 235, 250, 210, 190, 160, 200, 205, 222, 195, 205, 220, 220, 170, 185, 195, 220, 230, 180, 220, 180, 180, 170, 210, 215, 200, 213, 180, 192, 235, 185, 235, 210, 222, 210, 230, 220, 180, 190, 200, 210, 194, 180, 190, 240, 200, 198, 200, 195, 210, 220, 190, 210, 225, 180, 185, 170, 185, 185, 180, 178, 175, 200, 204, 211, 190, 210, 190, 190, 185, 290, 175, 185, 200, 220, 170, 220, 190, 220, 205, 200, 250, 225, 215, 210, 215, 195, 200, 194, 220, 180, 180, 170, 195, 180, 170, 206, 205, 200, 225, 201, 225, 233, 180, 225, 180, 220, 180, 237, 215, 190, 235, 190, 180, 165, 195, 200, 190, 190, 185, 185, 205, 190, 205, 206, 220, 208, 170, 195, 210, 190, 211, 230, 170, 185, 185, 241, 225, 210, 175, 230, 200, 215, 198, 226, 278, 215, 230, 240, 184, 219, 170, 218, 190, 225, 220, 176, 190, 197, 204, 167, 180, 195, 220, 215, 185, 190, 205, 205, 200, 210, 215, 200, 205, 211, 190, 208, 200, 210, 232, 230, 210, 220, 210, 202, 212, 225, 170, 190, 200, 237, 220, 170, 193, 190, 150, 220, 200, 190, 185, 185, 200, 172, 220, 225, 190, 195, 219, 190, 197, 200, 195, 210, 177, 220, 235, 180, 195, 195, 190, 230, 190, 200, 190, 190, 200, 200, 184, 200, 180, 219, 187, 200, 220, 205, 190, 170, 160, 215, 175, 205, 200, 214, 200, 190, 180, 205, 220, 190, 215, 235, 191, 200, 181, 200, 210, 240, 185, 165, 190, 185, 175, 155, 210, 170, 175, 220, 210, 205, 200, 205, 195, 240, 150, 200, 215, 202, 200, 190, 205, 190, 160, 215, 185, 200, 190, 210, 185, 220, 190, 202, 205, 220, 175, 160, 190, 200, 229, 206, 220, 180, 195, 175, 188, 230, 190, 200, 190, 219, 235, 180, 180, 180, 200, 234, 185, 220, 223, 200, 210, 200, 210, 190, 177, 227, 180, 195, 199, 175, 185, 240, 210, 180, 194, 225, 180, 205, 193, 230, 230, 220, 200, 249, 190, 208, 245, 250, 160, 192, 220, 170, 197, 155, 190, 200, 220, 210, 228, 190, 160, 184, 180, 180, 200, 176, 160, 222, 211, 195, 200, 175, 206, 240, 185, 260, 185, 221, 205, 200, 170, 201, 205, 185, 205, 245, 220, 210, 220, 185, 175, 170, 180, 200, 210, 175, 220, 206, 180, 210, 195, 200, 200, 164, 180, 220, 195, 205, 170, 240, 210, 195, 200, 205, 192, 190, 170, 240, 200, 205, 175, 250, 220, 224, 210, 195, 180, 245, 175, 180, 215, 175, 180, 195, 230, 230, 205, 215, 195, 180, 205, 180, 190, 180, 190, 190, 220, 210, 255, 190, 230, 200, 205, 210, 225, 215, 220, 205, 200, 220, 197, 225, 187, 245, 185, 185, 175, 200, 180, 188, 225, 200, 210, 245, 213, 231, 165, 228, 210, 250, 191, 190, 200, 215, 254, 232, 180, 215, 220, 180, 200, 170, 195, 210, 200, 220, 165, 180, 200, 200, 170, 224, 220, 180, 198, 240, 239, 185, 210, 220, 200, 195, 220, 230, 170, 220, 230, 165, 205, 192, 210, 205, 200, 210, 185, 195, 202, 205, 195, 180, 200, 185, 240, 185, 220, 205, 205, 180, 201, 190, 208, 240, 180, 230, 195, 215, 190, 195, 215, 215, 220, 220, 230, 195, 190, 195, 209, 204, 170, 185, 205, 175, 210, 190, 180, 180, 160, 235, 200, 210, 180, 190, 197, 203, 205, 170, 200, 250, 200, 220, 200, 190, 170, 190, 220, 215, 206, 215, 185, 235, 188, 230, 195, 168, 190, 160, 200, 200, 189, 180, 190, 200, 220, 187, 240, 190, 180, 185, 210, 220, 219, 190, 193, 175, 180, 215, 210, 200, 190, 185, 220, 170, 195, 205, 195, 210, 190, 190, 180, 220, 190, 186, 185, 190, 180, 190, 170, 210, 240, 220, 180, 210, 210, 195, 160, 180, 205, 200, 185, 245, 190, 210, 200, 200, 222, 215, 240, 170, 220, 156, 190, 202, 221, 200, 190, 210, 190, 200, 165, 190, 185, 230, 208, 209, 175, 180, 200, 205, 200, 250, 210, 230, 244, 202, 240, 200, 215, 177, 210, 170, 215, 217, 198, 200, 220, 170, 200, 230, 231, 183, 192, 167, 190, 180, 180, 215, 160, 205, 223, 175, 170, 190, 240, 175, 230, 223, 196, 167, 195, 190, 250, 190, 190, 190, 170, 160, 150, 225, 220, 209, 210, 176, 260, 195, 190, 184, 180, 195, 195, 219, 225, 212, 202, 185, 200, 209, 200, 195, 228, 210, 190, 212, 190, 218, 220, 190, 235, 210, 200, 188, 210, 235, 188, 215, 216, 220, 180, 185, 200, 210, 220, 185, 231, 210, 195, 200, 205, 200, 190, 250, 185, 180, 170, 180, 208, 235, 215, 244, 220, 185, 230, 190, 200, 180, 190, 196, 180, 230, 224, 160, 178, 205, 185, 210, 180, 190, 200, 257, 190, 220, 165, 205, 200, 208, 185, 215, 170, 235, 210, 170, 180, 170, 190, 150, 230, 203, 260, 246, 186, 210, 198, 210, 215, 180, 200, 245, 200, 192, 192, 200, 192, 205, 190, 186, 170, 197, 219, 200, 220, 207, 225, 207, 212, 225, 170, 190, 210, 230, 210, 200, 238, 234, 222, 200, 190, 170, 220, 223, 210, 215, 196, 175, 175, 189, 205, 210, 180, 180, 197, 220, 228, 190, 204, 165, 216, 220, 208, 210, 215, 195, 200, 215, 229, 240, 207, 205, 208, 185, 190, 170, 208, 225, 190, 225, 185, 180, 165, 240, 220, 212, 163, 215, 175, 205, 210, 205, 208, 215, 180, 200, 230, 211, 230, 190, 220, 180, 205, 190, 180, 205, 190, 195]

In [11]:
weights_lb= np.array(weights_lb)

In [12]:
weights_kg = weights_lb * 0.453592

In [13]:
# Converting weights in lbs to kg
weights_kg

array([81.64656, 97.52228, 95.25432, ..., 92.98636, 86.18248, 88.45044])

In [14]:
bmi = weights_kg / heights_in ** 2

In [15]:
# Calculate the BMI: bmi

bmi


array([23.11037639, 27.60406069, 28.48080465, ..., 25.62295933,
       23.74810865, 25.72686361])

<h4 style = "color : Sky blue"> Sub-Setting Arrays</h4>

##### Fetch the first element from the bmi array

In [16]:
print(bmi[0])

23.11037638875862


##### Fetch the last element from the bmi array

In [17]:
print(bmi[-1])

25.726863613607133


#####  Fetch the first 5 elements from the bmi array

In [18]:
bmi[:5]

array([23.11037639, 27.60406069, 28.48080465, 28.48080465, 24.80333518])

##### Fetch the last 5 elements from the bmi array

In [19]:
bmi[-5:]

array([25.06720044, 23.11037639, 25.62295933, 23.74810865, 25.72686361])

<h4 style = "color : Sky blue"> Conditional Sub-Setting Arrays</h4>

##### Count the number of pariticipants who are underweight i.e. bmi < 21


In [20]:
underweight = bmi < 21
underweight.sum()

np.int64(11)

In [21]:
print(underweight.sum())

11


<h4 style = "color : Sky blue"> NumPy Functions</h4>

##### Find the largest BMI value

In [22]:
greater =0
for i in bmi:
    if i > greater:
        greater = i
print(greater)

35.26194861031698


In [23]:
print(bmi.max())

35.26194861031698


##### Find lowest BMI value

In [24]:
print(bmi.min())

19.498447103560874


##### Find average BMI value

In [25]:
print(bmi.mean())

26.05684565448554


In [26]:
num_arr = np.arange(10,51)
num_arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [27]:
even_no =[]
for i in num_arr:
  if i % 2 == 0:
    even_no.append(i)
even_no=np.array(even_no)

In [28]:
even_no

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [29]:
randam_numbars=np.random.randint(0,25,size=25)
print(randam_numbars)

[ 7  5  9 18 14 13 11 22 19 24  1  9 22 11 24 22 24 22  7 15 19 24  0  2
  5]


In [30]:
# prompt: Provide an expression that sets A to be a 2*3 numpy array (2 rows by 3 columns), containing any values you wish.

import numpy as np
A = np.array([[1, 2, 3], [4, 5, 6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
def tp(A):
  B=np.transpose(A)
  print(B)

In [32]:
B=np.transpose(A)
B

array([[1, 4],
       [2, 5],
       [3, 6]])

In [33]:
m=np.array([1,2,3])

In [34]:
m.shape

(3,)

In [35]:
m=np.array([[1,2,3]])

In [36]:
m.shape

(1, 3)

In [37]:
n=np.array([1,2,3,4])

In [38]:
n=n*n

In [39]:
n

array([ 1,  4,  9, 16])

In [40]:
n = np.dot(n,n)

In [41]:
n

np.int64(354)

In [42]:
f=np.array([1,2,3,4])

In [43]:
f = np.dot(np.transpose(f), f)

In [44]:
f

np.int64(30)

In [45]:
a=np.array([[1,2,3,4],[5,6,7,8]])
b=np.array([[2,8,2,3],[1,2,4,1]])

In [46]:
d = np.dot(A, B)

In [47]:
d

array([[14, 32],
       [32, 77]])

In [48]:
e = np.array([1, 2]).tolist()
e

[1, 2]

In [49]:
A = np.array([[5,7,10,14],[2,4,8,9]])

In [50]:
A[0:1,1:3]

array([[ 7, 10]])

In [51]:
A[0:1,1:20]

array([[ 7, 10, 14]])

In [52]:
A[1:,:2]

array([[2, 4]])

In [53]:
A[1,1:3]

array([4, 8])

In [54]:
A[:, 1:2]

array([[7],
       [4]])

In [55]:
A[:, 1]

array([7, 4])

In [56]:
def rv(value_list):
  value_list = np.asarray(value_list).reshape(1,-1)
  print(value_list.shape)
  return value_list

In [57]:
value_lis = [1,2,3,4]
rv(value_list=value_lis)


(1, 4)


array([[1, 2, 3, 4]])

In [58]:
def rv(value_list):
  value_list = np.asarray(value_list).reshape(1,-1)
  print(value_list.shape)
  return value_list.T

In [59]:
value_lis = [1,2,3,4]
rv(value_list=value_lis)

(1, 4)


array([[1],
       [2],
       [3],
       [4]])

In [60]:
def length(col_v):
    return np.linalg.norm(col_v)

In [61]:
col = np.array([[3],[4]])
length(col_v= col)

np.float64(5.0)

In [62]:
def normalize(col_v):
    return col_v / length(col_v)

In [63]:
col = np.array([[3],[4]])
unit = normalize(col_v= col)
unit

array([[0.6],
       [0.8]])

In [64]:
def get_final_column(matrix):
    return matrix[:, [-1]]


In [65]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

final_column = get_final_column(A)
print(final_column)


[[3]
 [6]
 [9]]


In [66]:
def matrix_inverse(A):
    return np.linalg.inv(A)

In [67]:
A = np.array([[1, 2], [3, 4]])
inv_A = matrix_inverse(A)
print(inv_A)
print(np.dot(A, inv_A))

[[-2.   1. ]
 [ 1.5 -0.5]]
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


In [68]:
np.allclose(np.dot(A, inv_A), np.eye(2))  # Returns True


True

In [69]:
data = np.array([[150, 130, 120],
                 [5.8, 5.5, 5.3]])

In [70]:
data

array([[150. , 130. , 120. ],
       [  5.8,   5.5,   5.3]])

In [71]:
def transform(data):
    return np.dot(np.array([[1, 1]]), data)

result = transform(data)
print(result)  # Output: [[155.8 135.5 125.3]]

[[155.8 135.5 125.3]]


Assume we are given an input x as a column vector and the parameters specifying a linear hypothesis. Let's compute a predicted value.

In [72]:
def lin_reg_predict(x, th, th0):
    return np.array(np.dot(th.T, x) + th0)

In [73]:
x = np.array([[2], [3]])
th = np.array([[0.5], [1]])
th0 = 1.5

y = lin_reg_predict(x, th, th0)
print(y)

[[5.5]]


Now assume we are given n points in an array. Let's compute predictions for all of the points.

In [79]:
def lin_reg_predict(X, th, th0):
    return np.dot(th.T, X) + th0

In [75]:
X = np.array([[1, 2, 3], [4, 5, 6]])  # Shape: (2 x 3)
th = np.array([[0.5], [1]])          # Shape: (2 x 1)
th0 = 2                              # Scalar

y = lin_reg_predict(X, th, th0)
print(y)

[[6.5 8.  9.5]]


Linear Regression with Random Hypotheses

In [83]:
import numpy as np

# Function to compute mean squared errors for multiple hypotheses
def lin_reg_err(X, Y, thetas, th0s):
    preds = thetas.T @ X + th0s  # predictions shape: (k, n)
    errors = preds - Y
    mse = np.mean(errors ** 2, axis=1)  # mean squared error for each hypothesis
    return mse

# Function to generate k random hypotheses and return the best one
def random_regress(X, Y, k):
    d, n = X.shape
    thetas = 2 * np.random.rand(d, k) - 1
    th0s = 2 * np.random.rand(1, k) - 1
    errors = lin_reg_err(X, Y, thetas, th0s.T)
    i = np.argmin(errors)  # index of minimum error
    theta, th0 = thetas[:, i], th0s[:, i]
    return (theta, th0), errors[i]

# Simulate input data
np.random.seed(42)
d, n = 2, 100
X = np.random.rand(d, n)
true_theta = np.array([2.0, -3.5])
true_th0 = 1.0
Y = true_theta @ X + true_th0 + 0.1 * np.random.randn(n)
Y = Y.reshape(1, -1)

# Run the random regression function
k = 1000
(best_theta, best_th0), min_error = random_regress(X, Y, k)

print("Best theta:", best_theta)
print("Best th0:", best_th0)
print("Minimum MSE error:", min_error)


Best theta: [ 0.93638686 -0.84206168]
Best th0: [0.23260097]
Minimum MSE error: 0.6887658036976885
