In [1]:
import numpy as np

In [9]:
np.linspace(0,12,11)

array([ 0. ,  1.2,  2.4,  3.6,  4.8,  6. ,  7.2,  8.4,  9.6, 10.8, 12. ])

In [11]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [13]:
np.random.rand(2)

array([0.31423756, 0.45958466])

In [15]:
np.random.randn(2)

array([-0.86278749, -0.5512726 ])

In [17]:
np.random.seed(42)
np.random.rand(2)

array([0.37454012, 0.95071431])

In [19]:
np.random.seed(42)
np.random.randint(1,100,10)

array([52, 93, 15, 72, 61, 21, 83, 87, 75, 75])

In [23]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [25]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
arr[0]

array([1, 2, 3])

In [33]:
arr[::-1]

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [47]:
arr[1:3,0:2]

array([[4, 5],
       [7, 8]])

In [61]:
#matrix = np.array([np.arange(i, i+6) for i in range(0, 60, 10)])

#print(matrix)

In [63]:
matrix = np.arange(0, 60).reshape(6, 10)[:, 0:6]
print(matrix)

[[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]
 [40 41 42 43 44 45]
 [50 51 52 53 54 55]]


In [83]:
mat = []
for i in range(0,60):
    mat.append(i) 
    

In [85]:
mat

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59]